# Generated by Django 3.1 on 2020-12-29 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
            ],
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['title'], name='tenacity_te_title_cb80cc_idx'),
        ),
    ]
